version: '3'

services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react
    ports:
      - "3000:3000"

networks:
  # Join proxy network for exposing http services
  expose_network:
    external:
      name: web_proxy